#### these notes and more found @ https://realpython.com/flask-connexion-rest-api/

swagger: "2.0" # tells Connexion what version of the Swagger API is being used
info: 
  description: This is the swagger file that goes with our server code 
  version: "1.0.0" # a user defined version value for the API
  title: Truth Capture App # a user defined title included in the Connexion generated UI system
consumes: 
  - "application/json"
produces: 
  - "application/json"

basePath: "/api" 

# Paths supported by the server application
paths: 
  '/truths': 
    get: 
      operationId: "truths.read_all" # "truths.read_all" defines the Python import path/function that will respond to an HTTP GET /api/truths request. The "truths.read_all" portion can go as deep as you need to in order to connect a function to the HTTP request. Something like "<package_name>.<package_name>.<package_name>.<function_name>" would work just as well. 
      tags: 
        - "Truths"
      summary: "Read the entire list of truths" 
      description: "Read the list of truths" 
      parameters:
        - name: length
          in: query
          type: integer
          description: "Number of truths to get from truths"
          required: false
        - name: offset
          in: query
          type: integer
          description: "Offset from beginning of list where to start gathering truths"
          required: false
      # This section defines the section of the configuration of a successful response from the URL endpoint:
      responses: # defines the beginning of the expected response section
        200: # defines the section for a successful response, HTTP status code 200
          description: "Successfully read truths list operation" # defines the UI interface display text for a response of 200
          schema: # defines the response as a schema, or structure
            type: "array" # defines the structure of the schema as an array
            items: 
              properties: # defines the items in the array as objects having key/value pairs
                truthtext: # defines the first key of the object
                  type: "string" # defines the value associated with truthtext as a string
                hexcode: 
                  type: "string" 
                timestamp: 
                  type: "string" 

    post:
      operationId: truths.create
      tags:
        - Truths
      summary: Create a truth and add it to the truth list
      description: Create a truth in the truths list
      parameters:
        - name: truth
          in: body
          description: Truth to create
          required: True 
          schema:
            type: object
            properties:
              truthtext:
                type: string
                description: Text of truth to create
              hexcode:
                type: string
                description: Hex code (6 digit hexadecimal sequence) assigned to each truth, to associate each truth with a unique color and character sequence to identify it
      responses:
        201:
          description: Successfully created truth in list
  
  /truths/{hexcode}:
    get:
      operationId: truths.read_one
      tags:
        - Truths
      summary: Read one truth from the truths list
      description: Read one truth from the truths list
      parameters:
        - name: hexcode
          in: path
          description: Hexcode of the truth to get from the list
          type: string
          required: True 
      responses:
        200:
          description: Successfully read truth from truths list operation
          schema:
            properties:
              truthtext:
                type: string
              hexcode:
                type: string
              timestamp:
                type: string
    
    put:
      operationId: truths.update
      tags:
        - Truths
      summary: Update a truth in the truths list
      description: Update a truth in the truths list
      parameters:
        - name: hexcode
          in: path
          description: Hexcode of the truth to update in the truths list
          type: string
          required: True 
        - name: truth
          in: body
          schema:
            type: object
            properties:
              truthtext:
                type: string
              hexcode:
                type: string
      responses:
        200:
          description: Successfully updated truth in truths list
      
    delete:
      operationId: truths.delete
      tags:
        - Truths
      summary: Delete a truth from the truths list
      description: Delete a truth
      parameters:
        - name: hexcode
          in: path
          type: string
          required: True 
      responses:
        200:
          description: Successfully deleted a truth from truths list
